# Identificación de la app
spring.application.name=cloudnative

# Datos de Azure AD (Asegúrate de que AZURE_CLIENT_ID sea el ID del Backend: f72177e7...)
azure.activedirectory.tenant-id=${AZURE_TENANT_ID}
azure.activedirectory.client-id=${AZURE_CLIENT_ID}

# Base de Datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Validación Estándar de JWT en Spring Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0

# Ver logs detallados del fallo en la consola del EC2
logging.level.org.springframework.security=DEBUG